/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/sign.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.black_part.geometry}
        material={materials.lambert3SG}
        position={[-0.2, -0.41, 0.24]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.outline.geometry}
        material={materials['lambert3SG.001']}
        position={[-0.2, -0.17, 0.24]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh receiveShadow castShadow geometry={nodes.open.geometry} material={materials['lambert3SG.002']} position={[-0.2, -0.01, 0.24]} />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.opensign_turbo000.geometry}
        material={materials['lambert3SG.003']}
        position={[-0.2, -0.41, 0.24]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      {/* <directionalLight instensity={10} position={[-0.2, -0.41, 0.24]} castShadow/>
      <directionalLight instensity={10} position={[-0.2, -0.17, 0.24]} castShadow/> */}
    </group>
  )
}

useGLTF.preload('/sign.glb')