/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef, useState, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';
import { useSpring } from '@react-spring/core'
import { a } from '@react-spring/three'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/SignNeon.glb')
  const [expand, setExpand] = useState(null)
  const [size, setMaxSize] = useState()
  const ref = useRef()
  const rotation = [0, 6, 0]
  const scale = [-10, -10, -10]

  useFrame(() => (ref.current.rotation.y += 0.004))

  const animatedProps = useSpring({
    hovered: expand ? [size + 0.2, size + 0.2, size + 0.2] : [size, size, size]
  });

  useEffect(() => {
    const size = document.documentElement.clientWidth / 150
    if (size <= 6 ) {
      return setMaxSize(1.2)
    } 
    if (size >= 6 ) {
      return setMaxSize(1.6)
    }
},[])

useEffect(() => {
  set({ 
    rotation: [0, 0, 0],  
  })
})

  const [spring, set] = useSpring(() => ({
    scale: [...scale],
    rotation: [...rotation],
    config: { 
      mass: 10, 
      friction: 60, 
      tension: 100
    },
  }))


  return (
    <group ref={ref}>
    <a.group 
      ref={group} 
      {...props} 
      dispose={null} 
      {...spring} 
      scale={animatedProps.hovered}
      onPointerOver={() => setExpand(true)}
      onPointerLeave={() => setExpand(false)}
    >
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.opensign_turbo000_Sign.geometry}
        material={materials.lambert3SG}
        position={[-0.2, -0.41, 0.24]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.opensign_turbo001_LightsRed.geometry}
        material={materials['lambert3SG.002']}
        position={[-0.2, -0.41, 0.24]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.opensign_turbo001_LightsBlue.geometry}
        material={materials['lambert3SG.003']}
        position={[-0.2, -0.41, 0.24]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.opensign_turbo001_LightsBlueBlackPart.geometry}
        material={materials['lambert3SG.004']}
        position={[-0.2, -0.41, 0.24]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
      <mesh
        receiveShadow
        castShadow
        geometry={nodes.opensign_turbo001_LightsRedBlack.geometry}
        material={materials['lambert3SG.006']}
        position={[-0.2, -0.41, 0.24]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.04, 0.04, 0.04]}
      />
    </a.group>
    </group>
  )
}

useGLTF.preload('/SignNeon.glb')
